/// <reference path="./node_modules/nativewind/node_modules/react-native-css-interop/types.d.ts" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.